### ISSUE TITLE
Unable to share from closet

### ISSUE THREAD

**Issue by okaf1** [thelastbaldwin/auto_share#3]
Hi there, I've been using the bookmark for months now and it's recently started to not work. I used to be able to share from the general women's category, that stopped working. Today I noticed that it is no longer sharing my own closet, it is just scrolling to the bottom. I know Poshmark's framework probably changed but is there a fix? The only way I'm able to use this is on parties. I use chrome.

**Comment by thelastbaldwin** [comment]
I'm looking into this. I see that it's scrolling but it's no longer sharing

**Comment by thelastbaldwin** [comment]
So I ran the script on my end and it does appear to be working. I was able to observe a couple instances where the script continually scrolled to the bottom of the page and just didn't share any of the listings. There's really not enough information for me to deduce what's happening here. 
A partial workaround would be to manually scroll until your closet or page you're trying to load is fully loaded. Just keep scrolling until listings no longer load. This should force the script to scroll to the bottom of the page once, see the height hasn't changed (i.e. no more listings were loaded) and begin the share phase.

**Comment by okaf1** [comment]
Unfortunately that and changing to 1000 didn’t work for me. It just sits at the bottom of the page. Sometimes when it was stuck before I would click the search bar and it would start up, but not the case now. Maybe it’s my chrome or something on my end. I appreciate you looking into it.

**Comment by thelastbaldwin** [comment]
The last thing I can think of is to scroll until you no longer have active listings, and manually replace this block: 
```
  let lastWindowHeight = getWindowHeight();

  const checkHeightAndScroll = () => {
    const newHeight = getWindowHeight();

    if (newHeight !== lastWindowHeight) {
      lastWindowHeight = newHeight;
      scrollToBottomOfPage();
    } else {
      window.removeEventListener(ajaxSuccessEvent, checkHeightAndScroll);
      shareActiveListings();
    }
  };

  window.addEventListener(ajaxSuccessEvent, checkHeightAndScroll);
  scrollToBottomOfPage();
```

with this: 
```
shareActiveListings()
```

That will completely sidestep all of the scrolling logic and should only share you items. 
You can either create a new bookmarklet from this code or try to run this in the console. Please remember to manually scroll until all your content is loaded: 
```
(function () {
  const inventoryTagClass = ".inventory-tag";
  const shareButtonClass = ".share";
  const shareModalId = "#share-popup";
  const followerShareClass = ".pm-followers-share-link";

  const isVisible = (el) =>
    el.offsetParent !== null || getComputedStyle(el).display !== "none";
  const getCaptchaElement = () => document.querySelector("#captcha-popup");
  const getAllTiles = () => document.querySelectorAll(".tile");
  const getActiveTiles = () => {
    const allTiles = getAllTiles();
    return Array.prototype.filter.call(
      allTiles,
      (tile) => tile.querySelector(inventoryTagClass) === null
    );
  };
  const getShareButton = (t) => t.querySelector(shareButtonClass);

  const shareActiveListings = () => {
    const shareModal = document.querySelector(shareModalId);
    const shareToFollowersButton = shareModal.querySelector(followerShareClass);
    const activeTiles = getActiveTiles();
    let currentTileIndex = 0;
    let captchaEl = getCaptchaElement();

    const shareNextActiveTile = () => {
      captchaEl = captchaEl || getCaptchaElement();

      if (!captchaEl || !isVisible(captchaEl)) {
        const currentTile = activeTiles[currentTileIndex++];
        const shareButton = getShareButton(currentTile);

        shareButton.click();
        shareToFollowersButton.click();
      }

      if (currentTileIndex < activeTiles.length) {
        window.setTimeout(shareNextActiveTile, 500);
      }
    };
    shareNextActiveTile();
  };

  shareActiveListings();
})();
```

**Comment by okaf1** [comment]
I tried it on another account, and it works. I’ve concluded it must be my account that’s not letting me do it. Which is odd. Thanks again!

**Comment by btannous** [comment]
I think posh is A/B testing something here as I'm also running into this issue.

**Comment by btannous** [comment]
@okaf1 try this
Note, this also bypasses the autoscroll for the moment and I haven't gotten a captcha yet but it's working here.

```javascript
(function () {
    const inventoryTagClass = ".inventory-tag";
    const shareButtonClass = ".social-action-bar__share";
    const shareModalId = ".internal-share-container";
    const followerShareClass = ".share-wrapper-container";
  
    const isVisible = (el) =>
      el.offsetParent !== null || getComputedStyle(el).display !== "none";
    const getCaptchaElement = () => document.querySelector("#captcha-popup");
    const getAllTiles = () => document.querySelectorAll(".tile");
    const getActiveTiles = () => {
      const allTiles = getAllTiles();
      return Array.prototype.filter.call(
        allTiles,
        (tile) => tile.querySelector(inventoryTagClass) === null
      );
    };
    const getShareButton = (t) => t.querySelector(shareButtonClass);

    const shareActiveListings = () => {
      const activeTiles = getActiveTiles();
      currentTileIndex = 0;
      let captchaEl = getCaptchaElement();
  
      const shareToFollowers = () =>  {
        if (document.querySelector(shareModalId)) {
            document.querySelector(shareModalId).querySelector(followerShareClass).click();
            if (currentTileIndex < activeTiles.length) {
                console.log(currentTileIndex);
                window.setTimeout(shareNextActiveTile, 1000);
            }
        } else {
            window.setTimeout(shareToFollowers, 300);
        }
      }

      const shareNextActiveTile = () => {
        captchaEl = captchaEl || getCaptchaElement();
  
        if (!captchaEl || !isVisible(captchaEl)) {
          const currentTile = activeTiles[currentTileIndex++];
          const shareButton = getShareButton(currentTile);
  
          shareButton.click();

          window.setTimeout(shareToFollowers, 300); // wait for the modal to pop up
        }
      };
      shareNextActiveTile();
    };
  
    shareActiveListings();
  })();
```

**Comment by thelastbaldwin** [comment]
@btannous I've pushed some changes to master, which are somewhat similar to yours. I've made an enhancement to the script so it stops loading new pages of the closet when the last tile contains an inventory tag. I've yet to see an instance of an active listing mixed with not for sale and sold items so I think this is safe. 

@okaf1 The updated script should work now

**Comment by thelastbaldwin** [comment]
@btannous It looks like the last holdout is solving for a race condition between clicking the share button and when the share modal shows up. I'm looking into a way to use an await + MutationObserver on the main tag for when the modal shows up to avoid using timers.

**Comment by thelastbaldwin** [comment]
I've pushed new code that solves for the presence of the modal without the use of timers. I've tested this a few times as a bookmarklet and from the console and have not had any issues.

**Comment by okaf1** [comment]
It works in the console now! Thanks so much. Still doesn't work via bookmarklet but I'm happy its running!

**Comment by thelastbaldwin** [comment]
@okaf1 Excellent. Be sure to update your bookmarklet with the new code. I wouldn't expect the old one to work.

**Comment by rafiks** [comment]
is this still working?

**Comment by btannous** [comment]
I'm back on the old site, seems my a/b test is back. try this:
https://github.com/thelastbaldwin/auto_share/blob/03421e116497fbe6c27f2b0362fb452f565ae941/auto_share.js

**Comment by thelastbaldwin** [comment]
@btannous I've reverted the master branch to the commit you listed. I've preserved the AB changes in a separate branch if they're needed in the future. Thanks for keeping an eye on this code!
